application: noc-sites
version: 1
runtime: python27
api_version: 1

threadsafe: false

handlers:

- url: /static
  static_dir: bootstrap
  
- url: /.*
  script: noc.py
  
  
  

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
  
- name: webapp2
  version: latest
